version: "3.8"

services:
#  app:
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - "3005:3000"
#    env_file:
#      - .env
#    volumes:
#      - ./:/app
#      - /app/node_modules
#      - /app/.next
#    environment:
#      - NODE_ENV=development
#      - WATCHPACK_POLLING=true
#      - CHOKIDAR_USEPOLLING=true
#    stdin_open: true
#    tty: true
#    networks:
#      rm:

  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token eyJhIjoiMGEzNmUyZjMwZmVhNTE5M2M0MGZhNGI4YTRlNDE1MjkiLCJ0IjoiYWYxMTdiMDktZGRjZC00NDBiLWJjMDgtYTA5OTM1ZDA5MWQwIiwicyI6IlpXUm1PV1ZsTTJJdE5HRm1OUzAwWVRjMkxUZzFaR010WlRZM01UUTROMkV3WkRZMSJ9
    restart: unless-stopped



networks:
  rm:


